version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongo_data:
