name: Sync README to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload README to DockerHub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: chrisimkim/web-app
          readme-filepath: README.md
