name: Web App CI/CD

on:
  push:
    paths:
      - 'web-app/**'
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd web-app
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          cd web-app
          pytest --cov=. --cov-report=term-missing

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest ./web-app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
