name: Web App CI/CD

on:
  push:
    paths:
      - 'web-app/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd web-app
          pip install -r requirements.txt

      - name: Run tests
        env:
          FLASK_ENV: testing 
        run: |
          cd web-app
          pytest --cov=.
